// Generates supabase/seed.sql from data/seed-data.ts (idempotent: truncates and reloads).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { MENTEES, MENTORS, SKILLS } from "../data/seed-data";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (xs: string[]) => `array[${xs.map(q).join(", ")}]::text[]`;

const skillNames = new Set(SKILLS.map((s) => s.name));
for (const p of [...MENTORS.map((m) => m.skills), ...MENTEES.map((m) => m.goals)]) {
  for (const name of Object.keys(p)) {
    if (!skillNames.has(name)) throw new Error(`Unknown skill in seed data: ${name}`);
  }
}

const lines: string[] = [
  "-- GENERATED by scripts/gen-seed-sql.ts from data/seed-data.ts. Do not edit by hand.",
  "begin;",
  "truncate mentee_goal_skills, mentor_skills, mentees, mentors, skills restart identity cascade;",
  "",
  "insert into skills (name, category) values",
  SKILLS.map((s) => `  (${q(s.name)}, ${q(s.category)})`).join(",\n") + ";",
  "",
  "insert into mentors (id, name, headline, bio, industry, years_experience, timezone_offset, languages, format, city, availability, max_mentees) values",
  MENTORS.map(
    (m) =>
      `  (${q(m.id)}, ${q(m.name)}, ${q(m.headline)}, ${q(m.bio)}, ${q(m.industry)}, ${m.years_experience}, ${m.timezone_offset}, ${arr(m.languages)}, ${q(m.format)}, ${q(m.city)}, ${arr(m.availability)}, ${m.max_mentees})`,
  ).join(",\n") + ";",
  "",
  "insert into mentees (id, name, goal_summary, career_stage, industry, desired_min_years, timezone_offset, languages, format, city, availability) values",
  MENTEES.map(
    (m) =>
      `  (${q(m.id)}, ${q(m.name)}, ${q(m.goal_summary)}, ${q(m.career_stage)}, ${q(m.industry)}, ${m.desired_min_years}, ${m.timezone_offset}, ${arr(m.languages)}, ${q(m.format)}, ${q(m.city)}, ${arr(m.availability)})`,
  ).join(",\n") + ";",
  "",
  "insert into mentor_skills (mentor_id, skill_id, proficiency)",
  "select v.mentor_id, s.id, v.proficiency from (values",
  MENTORS.flatMap((m) =>
    Object.entries(m.skills).map(([name, p]) => `  (${q(m.id)}, ${q(name)}, ${p})`),
  ).join(",\n"),
  ") as v(mentor_id, skill_name, proficiency) join skills s on s.name = v.skill_name;",
  "",
  "insert into mentee_goal_skills (mentee_id, skill_id, priority)",
  "select v.mentee_id, s.id, v.priority from (values",
  MENTEES.flatMap((m) =>
    Object.entries(m.goals).map(([name, p]) => `  (${q(m.id)}, ${q(name)}, ${p})`),
  ).join(",\n"),
  ") as v(mentee_id, skill_name, priority) join skills s on s.name = v.skill_name;",
  "",
  "commit;",
  "",
];

const dir = join(__dirname, "..", "supabase");
const seed = lines.join("\n");
writeFileSync(join(dir, "seed.sql"), seed);
console.log(`Wrote supabase/seed.sql: ${SKILLS.length} skills, ${MENTORS.length} mentors, ${MENTEES.length} mentees`);

// One-paste setup for the Supabase SQL editor: migrations + seed, in order. Safe to re-run.
const migrations = ["0001_schema.sql", "0002_rag.sql", "0003_roles.sql", "0004_admin_features.sql"].map((m) => readFileSync(join(dir, "migrations", m), "utf8"));
writeFileSync(
  join(dir, "setup.sql"),
  ["-- GENERATED by scripts/gen-seed-sql.ts: migrations + seed in one file.", ...migrations, seed, "notify pgrst, 'reload schema';", ""].join("\n\n"),
);
console.log("Wrote supabase/setup.sql");
