-- GENERATED by scripts/gen-seed-sql.ts: migrations + seed in one file.

-- Serene Mentors: relational product data (Supabase Postgres)
-- Access model: every table has RLS enabled and NO policies for anon/authenticated,
-- so only the server (Supabase secret key / service_role, after verifying the Firebase ID token) can read/write.

create extension if not exists pgcrypto;

-- App users, keyed by Firebase UID (identity provider is Firebase Auth, not Supabase Auth)
create table if not exists app_users (
  id            uuid primary key default gen_random_uuid(),
  firebase_uid  text not null unique,
  email         text,
  display_name  text,
  created_at    timestamptz not null default now(),
  last_seen_at  timestamptz not null default now()
);

create table if not exists skills (
  id        serial primary key,
  name      text not null unique,
  category  text not null
);

-- Dataset B: mentors (candidates to be ranked)
create table if not exists mentors (
  id                text primary key,              -- e.g. 'mentor-01'
  name              text not null,
  headline          text not null,
  bio               text not null,
  industry          text not null,
  years_experience  int  not null check (years_experience >= 0),
  timezone_offset   numeric(4,2) not null check (timezone_offset between -12 and 14),
  languages         text[] not null default '{}',
  format            text not null check (format in ('remote','in_person','hybrid')),
  city              text not null,
  availability      text[] not null default '{}', -- e.g. {'weekday_evening','weekend_morning'}
  max_mentees       int  not null default 3 check (max_mentees > 0)
);

-- Dataset A: mentees (source profiles a user selects)
create table if not exists mentees (
  id                 text primary key,             -- e.g. 'mentee-01'
  name               text not null,
  goal_summary       text not null,
  career_stage       text not null,
  industry           text not null,
  desired_min_years  int  not null default 0 check (desired_min_years >= 0),
  timezone_offset    numeric(4,2) not null check (timezone_offset between -12 and 14),
  languages          text[] not null default '{}',
  format             text not null check (format in ('remote','in_person','hybrid')),
  city               text not null,
  availability       text[] not null default '{}'
);

create table if not exists mentor_skills (
  mentor_id    text not null references mentors(id) on delete cascade,
  skill_id     int  not null references skills(id)  on delete cascade,
  proficiency  int  not null check (proficiency between 1 and 5),
  primary key (mentor_id, skill_id)
);

create table if not exists mentee_goal_skills (
  mentee_id  text not null references mentees(id) on delete cascade,
  skill_id   int  not null references skills(id)  on delete cascade,
  priority   int  not null check (priority between 1 and 3), -- 3 = must-have
  primary key (mentee_id, skill_id)
);

create index if not exists mentor_skills_skill_idx on mentor_skills(skill_id);
create index if not exists mentee_goal_skills_skill_idx on mentee_goal_skills(skill_id);

alter table app_users          enable row level security;
alter table skills             enable row level security;
alter table mentors            enable row level security;
alter table mentees            enable row level security;
alter table mentor_skills      enable row level security;
alter table mentee_goal_skills enable row level security;


-- RAG knowledge base storage with pgvector
create extension if not exists vector;

create table if not exists kb_documents (
  id          serial primary key,
  slug        text not null unique,
  title       text not null,
  source      text not null,           -- file path in repo, e.g. kb/handbook.md
  updated_at  timestamptz not null default now()
);

create table if not exists kb_chunks (
  id               bigserial primary key,
  document_id      int  not null references kb_documents(id) on delete cascade,
  chunk_index      int  not null,
  heading          text not null,
  content          text not null,
  content_hash     text not null unique,  -- sha256(model + doc + heading + content): idempotent ingest
  embedding_model  text not null,
  embedding        vector(768) not null,
  created_at       timestamptz not null default now()
);

create index if not exists kb_chunks_doc_idx on kb_chunks(document_id);
create index if not exists kb_chunks_embedding_idx
  on kb_chunks using hnsw (embedding vector_cosine_ops);

alter table kb_documents enable row level security;
alter table kb_chunks    enable row level security;

-- Top-k cosine similarity search, filtered by a minimum similarity threshold
create or replace function match_kb_chunks(
  query_embedding vector(768),
  match_count     int   default 5,
  min_similarity  float default 0.5
)
returns table (
  id          bigint,
  document_id int,
  title       text,
  slug        text,
  heading     text,
  content     text,
  similarity  float
)
language sql stable
as $$
  select c.id, c.document_id, d.title, d.slug, c.heading, c.content,
         1 - (c.embedding <=> query_embedding) as similarity
  from kb_chunks c
  join kb_documents d on d.id = c.document_id
  where 1 - (c.embedding <=> query_embedding) >= min_similarity
  order by c.embedding <=> query_embedding
  limit least(greatest(match_count, 1), 20);
$$;

-- Lock the function down to the server role
revoke execute on function match_kb_chunks(vector, int, float) from public, anon, authenticated;
grant execute on function match_kb_chunks(vector, int, float) to service_role;


-- GENERATED by scripts/gen-seed-sql.ts from data/seed-data.ts. Do not edit by hand.
begin;
truncate mentee_goal_skills, mentor_skills, mentees, mentors, skills restart identity cascade;

insert into skills (name, category) values
  ('React', 'Engineering'),
  ('TypeScript', 'Engineering'),
  ('Node.js', 'Engineering'),
  ('System Design', 'Engineering'),
  ('Testing', 'Engineering'),
  ('Go', 'Engineering'),
  ('Mobile Development', 'Engineering'),
  ('Python', 'Data'),
  ('Machine Learning', 'Data'),
  ('SQL', 'Data'),
  ('Data Visualization', 'Data'),
  ('Cloud Architecture', 'Infrastructure'),
  ('DevOps', 'Infrastructure'),
  ('Kubernetes', 'Infrastructure'),
  ('Application Security', 'Infrastructure'),
  ('UX Research', 'Design'),
  ('UI Design', 'Design'),
  ('Design Systems', 'Design'),
  ('Product Strategy', 'Product'),
  ('Roadmapping', 'Product'),
  ('Leadership', 'Career'),
  ('Public Speaking', 'Career'),
  ('Interviewing', 'Career'),
  ('Marketing Analytics', 'Growth'),
  ('Content Strategy', 'Growth'),
  ('Fundraising', 'Business');

insert into mentors (id, name, headline, bio, industry, years_experience, timezone_offset, languages, format, city, availability, max_mentees) values
  ('mentor-01', 'Dr. Priya Raman', 'Principal Frontend Engineer, Lumen Labs', 'Fourteen years building large React applications; leads frontend architecture reviews and testing strategy.', 'Software', 14, 5.5, array['English', 'Hindi', 'Tamil']::text[], 'remote', 'Bengaluru', array['weekday_evening', 'weekend_morning']::text[], 3),
  ('mentor-02', 'Marcus Bell', 'Staff Engineer, Northwind Apps', 'React and TypeScript specialist who enjoys mentoring juniors through their first big refactor.', 'Software', 11, -5, array['English']::text[], 'remote', 'New York', array['weekday_evening', 'weekend_afternoon']::text[], 2),
  ('mentor-03', 'Chen Wei', 'Engineering Manager, Harbor Cloud', 'Former backend lead now managing platform teams; focuses on system design interviews and leadership.', 'Software', 16, 8, array['English', 'Mandarin']::text[], 'hybrid', 'Singapore', array['weekday_morning', 'weekend_morning']::text[], 3),
  ('mentor-04', 'Sofia Martins', 'Senior Data Scientist, Atlas Retail', 'Builds demand-forecasting models; passionate about teaching practical machine learning and SQL.', 'Data', 9, 0, array['English', 'Portuguese', 'Spanish']::text[], 'remote', 'Lisbon', array['weekday_evening', 'weekend_morning']::text[], 3),
  ('mentor-05', 'Kwame Asante', 'Head of Product, Kinetic Pay', 'Product leader in fintech who has shipped payments products across three continents.', 'Fintech', 13, 0, array['English', 'French']::text[], 'remote', 'Accra', array['weekday_evening', 'weekday_afternoon']::text[], 2),
  ('mentor-06', 'Elena Petrova', 'Design Director, Brightside Studio', 'Leads a design team building accessible design systems for consumer apps.', 'Design', 12, 1, array['English', 'Russian']::text[], 'hybrid', 'Berlin', array['weekday_afternoon', 'weekday_evening']::text[], 3),
  ('mentor-07', 'Rahul Mehta', 'Senior Backend Engineer, Parcelly', 'Node.js and distributed systems engineer who loves code review and testing culture.', 'Software', 8, 5.5, array['English', 'Hindi', 'Gujarati']::text[], 'remote', 'Pune', array['weekday_evening', 'weekend_afternoon']::text[], 3),
  ('mentor-08', 'Hannah Okafor', 'Security Engineer, Shieldline', 'Application security engineer focused on secure-by-default web platforms.', 'Cybersecurity', 10, 1, array['English']::text[], 'remote', 'Lagos', array['weekday_evening', 'weekend_morning']::text[], 2),
  ('mentor-09', 'Lucas Moreau', 'Platform Lead, Vela Systems', 'Runs Kubernetes platforms at scale and teaches DevOps fundamentals.', 'Software', 15, 1, array['English', 'French']::text[], 'in_person', 'Paris', array['weekday_morning', 'weekday_afternoon']::text[], 2),
  ('mentor-10', 'Aiko Tanaka', 'Mobile Engineering Lead, Sakura Health Apps', 'Leads cross-platform mobile teams and cares deeply about testing and release quality.', 'Software', 10, 9, array['English', 'Japanese']::text[], 'remote', 'Tokyo', array['weekday_evening', 'weekend_morning']::text[], 3),
  ('mentor-11', 'Isabella Rossi', 'Growth Marketing Manager, Fiora', 'Data-informed marketer who builds content and analytics programmes for startups.', 'Marketing', 7, 1, array['English', 'Italian']::text[], 'remote', 'Milan', array['weekday_afternoon', 'weekday_evening']::text[], 3),
  ('mentor-12', 'Daniel Kim', 'Founder & CEO, Pebble Learning', 'Second-time founder in edtech; advises early-stage founders on fundraising and pitching.', 'Education', 12, -8, array['English', 'Korean']::text[], 'remote', 'San Francisco', array['weekday_evening', 'weekend_morning']::text[], 2),
  ('mentor-13', 'Fatima Zahra', 'ML Engineer, Oasis AI', 'Deploys machine learning models to production and mentors career switchers into data roles.', 'Data', 7, 4, array['English', 'Arabic', 'French']::text[], 'remote', 'Dubai', array['weekday_evening', 'weekend_afternoon']::text[], 3),
  ('mentor-14', 'Oliver Grant', 'Senior Product Designer, Meadow', 'Product designer with a research-first approach and a love of rapid prototyping.', 'Design', 6, 0, array['English']::text[], 'hybrid', 'London', array['weekday_evening', 'weekend_morning']::text[], 3),
  ('mentor-15', 'Ananya Iyer', 'Data Analytics Manager, Spice Route Foods', 'Turns messy business data into dashboards that people actually use.', 'Data', 9, 5.5, array['English', 'Tamil', 'Hindi']::text[], 'remote', 'Chennai', array['weekday_evening', 'weekend_morning']::text[], 3),
  ('mentor-16', 'Mateo García', 'Engineering Director, Rumbo', 'Grew an engineering org from 5 to 80 people; mentors new managers.', 'Software', 18, -3, array['English', 'Spanish']::text[], 'remote', 'Buenos Aires', array['weekday_evening', 'weekday_afternoon']::text[], 2),
  ('mentor-17', 'Grace Liu', 'Frontend Engineer, Inkwell', 'Early-career friendly mentor focused on modern React, TypeScript and accessibility.', 'Software', 5, 8, array['English', 'Mandarin']::text[], 'remote', 'Taipei', array['weekday_evening', 'weekend_afternoon']::text[], 4),
  ('mentor-18', 'Samuel Adeyemi', 'Cloud Solutions Architect, Baobab Cloud', 'Designs cloud architectures for scale-ups and teaches cost-aware infrastructure.', 'Software', 12, 1, array['English', 'Yoruba']::text[], 'remote', 'Lagos', array['weekend_morning', 'weekend_afternoon']::text[], 3),
  ('mentor-19', 'Nora Lindqvist', 'Product Manager, Fjord Climate', 'PM in climate tech who mentors on discovery, roadmaps and stakeholder communication.', 'Climate', 8, 1, array['English', 'Swedish']::text[], 'remote', 'Stockholm', array['weekday_afternoon', 'weekday_evening']::text[], 3),
  ('mentor-20', 'Arjun Nair', 'Senior SRE, Monsoon Tech', 'Site reliability engineer passionate about observability and on-call health.', 'Software', 9, 5.5, array['English', 'Malayalam', 'Hindi']::text[], 'remote', 'Kochi', array['weekday_morning', 'weekend_afternoon']::text[], 3),
  ('mentor-21', 'Chloe Dubois', 'Content Lead, Papier', 'Editorial strategist who coaches writers moving into content marketing.', 'Marketing', 10, 1, array['English', 'French']::text[], 'hybrid', 'Lyon', array['weekday_morning', 'weekday_afternoon']::text[], 3),
  ('mentor-22', 'Yusuf Demir', 'Backend Engineer, Bosphorus Logistics', 'Go and SQL engineer who enjoys pairing on system design problems.', 'Software', 6, 3, array['English', 'Turkish']::text[], 'remote', 'Istanbul', array['weekday_evening', 'weekend_morning']::text[], 3),
  ('mentor-23', 'Maya Goldberg', 'VP Engineering, Cedar Health Tech', 'Engineering leader in health-tech software (non-clinical) who mentors on leadership and hiring.', 'Software', 20, 2, array['English', 'Hebrew']::text[], 'remote', 'Tel Aviv', array['weekday_evening']::text[], 2),
  ('mentor-24', 'Tomás Silva', 'Fintech Data Engineer, Coral Bank', 'Builds data pipelines for regulated finance; mentors on SQL and Python.', 'Fintech', 8, -3, array['English', 'Portuguese']::text[], 'remote', 'São Paulo', array['weekday_evening', 'weekend_morning']::text[], 3),
  ('mentor-25', 'Leila Haddad', 'UX Researcher, Cedarline', 'Mixed-methods researcher who helps designers and PMs run better interviews.', 'Design', 7, 2, array['English', 'Arabic', 'French']::text[], 'remote', 'Beirut', array['weekday_evening', 'weekend_morning']::text[], 3),
  ('mentor-26', 'Ben Carter', 'Developer Advocate, Quill Docs', 'Speaker and educator who helps engineers grow their public profile.', 'Software', 9, -5, array['English']::text[], 'remote', 'Toronto', array['weekday_afternoon', 'weekend_afternoon']::text[], 4),
  ('mentor-27', 'Zara Ahmed', 'Product Analytics Lead, Lantern Ed', 'Edtech analytics lead focused on experimentation and product metrics.', 'Education', 8, 5, array['English', 'Urdu']::text[], 'remote', 'Karachi', array['weekday_evening', 'weekend_morning']::text[], 3),
  ('mentor-28', 'Ivan Horvat', 'Security Architect, Adriatic Systems', 'Security architect who mentors on threat modelling and secure cloud design.', 'Cybersecurity', 14, 1, array['English', 'Croatian']::text[], 'in_person', 'Zagreb', array['weekday_morning']::text[], 2),
  ('mentor-29', 'Mei Lin Wong', 'Design Systems Engineer, Prism', 'Bridges design and engineering by building component libraries in React.', 'Design', 7, 8, array['English', 'Cantonese']::text[], 'remote', 'Hong Kong', array['weekday_evening', 'weekend_morning']::text[], 3),
  ('mentor-30', 'Peter Novak', 'Startup Advisor, Danube Ventures', 'Former founder turned angel investor; mentors on fundraising and early product strategy.', 'Fintech', 17, 1, array['English', 'Czech', 'German']::text[], 'hybrid', 'Prague', array['weekday_afternoon', 'weekend_morning']::text[], 2);

insert into mentees (id, name, goal_summary, career_stage, industry, desired_min_years, timezone_offset, languages, format, city, availability) values
  ('mentee-01', 'Aisha Khan', 'Mid-level frontend developer aiming for a senior role; wants to master React architecture, system design and testing.', 'Mid-level', 'Software', 10, 5.5, array['English', 'Hindi', 'Urdu']::text[], 'remote', 'Hyderabad', array['weekday_evening', 'weekend_morning']::text[]),
  ('mentee-02', 'Liam O''Connor', 'Analyst moving into data science; wants hands-on machine learning and Python practice.', 'Career switcher', 'Data', 5, 0, array['English']::text[], 'remote', 'Dublin', array['weekday_evening', 'weekend_morning']::text[]),
  ('mentee-03', 'Sara Johansson', 'Junior designer who wants to grow in design systems and UI craft.', 'Junior', 'Design', 5, 1, array['English', 'Swedish']::text[], 'hybrid', 'Gothenburg', array['weekday_afternoon', 'weekday_evening']::text[]),
  ('mentee-04', 'Diego Fernández', 'First-time founder preparing a seed round; needs help with fundraising and pitching.', 'Founder', 'Fintech', 10, -3, array['English', 'Spanish']::text[], 'remote', 'Montevideo', array['weekday_evening', 'weekend_morning']::text[]),
  ('mentee-05', 'Ngozi Eze', 'Backend developer who wants to move into cloud and DevOps engineering.', 'Mid-level', 'Software', 8, 1, array['English']::text[], 'remote', 'Abuja', array['weekend_morning', 'weekend_afternoon']::text[]),
  ('mentee-06', 'Kenji Watanabe', 'Newly promoted tech lead learning to lead people and run interviews.', 'New manager', 'Software', 12, 9, array['English', 'Japanese']::text[], 'remote', 'Osaka', array['weekday_morning', 'weekend_morning']::text[]),
  ('mentee-07', 'Amara Diallo', 'Marketing coordinator who wants to become data-driven with analytics and content strategy.', 'Junior', 'Marketing', 5, 0, array['English', 'French']::text[], 'remote', 'Dakar', array['weekday_afternoon', 'weekday_evening']::text[]),
  ('mentee-08', 'Rohan Gupta', 'Associate PM who wants stronger product strategy and roadmapping skills.', 'Associate', 'Fintech', 8, 5.5, array['English', 'Hindi']::text[], 'remote', 'Mumbai', array['weekday_evening', 'weekday_afternoon']::text[]),
  ('mentee-09', 'Emily Clarke', 'Web developer interested in application security and secure cloud design.', 'Mid-level', 'Cybersecurity', 8, 0, array['English']::text[], 'remote', 'Manchester', array['weekday_evening', 'weekend_morning']::text[]),
  ('mentee-10', 'Hira Baig', 'Junior data analyst who wants to level up SQL and dashboarding.', 'Junior', 'Data', 5, 5, array['English', 'Urdu']::text[], 'remote', 'Lahore', array['weekday_evening', 'weekend_morning']::text[]),
  ('mentee-11', 'Tom Becker', 'Bootcamp graduate looking for guidance on React, TypeScript and landing a first job.', 'Entry-level', 'Software', 3, 8, array['English', 'German']::text[], 'remote', 'Perth', array['weekday_evening', 'weekend_afternoon']::text[]),
  ('mentee-12', 'Lucía Morales', 'UX designer moving into research-led product discovery.', 'Mid-level', 'Design', 6, 2, array['English', 'Spanish']::text[], 'remote', 'Madrid', array['weekday_evening', 'weekend_morning']::text[]);

insert into mentor_skills (mentor_id, skill_id, proficiency)
select v.mentor_id, s.id, v.proficiency from (values
  ('mentor-01', 'React', 5),
  ('mentor-01', 'System Design', 5),
  ('mentor-01', 'Testing', 4),
  ('mentor-01', 'TypeScript', 5),
  ('mentor-01', 'Leadership', 3),
  ('mentor-02', 'React', 5),
  ('mentor-02', 'TypeScript', 5),
  ('mentor-02', 'Testing', 3),
  ('mentor-02', 'Node.js', 4),
  ('mentor-03', 'System Design', 5),
  ('mentor-03', 'Go', 4),
  ('mentor-03', 'Leadership', 5),
  ('mentor-03', 'Interviewing', 4),
  ('mentor-03', 'Cloud Architecture', 4),
  ('mentor-04', 'Python', 5),
  ('mentor-04', 'Machine Learning', 5),
  ('mentor-04', 'SQL', 4),
  ('mentor-04', 'Data Visualization', 3),
  ('mentor-05', 'Product Strategy', 5),
  ('mentor-05', 'Roadmapping', 5),
  ('mentor-05', 'Leadership', 4),
  ('mentor-05', 'Public Speaking', 4),
  ('mentor-06', 'UI Design', 5),
  ('mentor-06', 'Design Systems', 5),
  ('mentor-06', 'UX Research', 4),
  ('mentor-06', 'Leadership', 4),
  ('mentor-07', 'Node.js', 5),
  ('mentor-07', 'System Design', 4),
  ('mentor-07', 'Testing', 4),
  ('mentor-07', 'SQL', 4),
  ('mentor-07', 'React', 2),
  ('mentor-08', 'Application Security', 5),
  ('mentor-08', 'Cloud Architecture', 4),
  ('mentor-08', 'DevOps', 3),
  ('mentor-08', 'Node.js', 3),
  ('mentor-09', 'Kubernetes', 5),
  ('mentor-09', 'DevOps', 5),
  ('mentor-09', 'Cloud Architecture', 5),
  ('mentor-09', 'Go', 4),
  ('mentor-10', 'Mobile Development', 5),
  ('mentor-10', 'React', 4),
  ('mentor-10', 'TypeScript', 4),
  ('mentor-10', 'Testing', 4),
  ('mentor-11', 'Marketing Analytics', 5),
  ('mentor-11', 'Content Strategy', 5),
  ('mentor-11', 'Data Visualization', 3),
  ('mentor-12', 'Fundraising', 5),
  ('mentor-12', 'Public Speaking', 5),
  ('mentor-12', 'Product Strategy', 4),
  ('mentor-12', 'Leadership', 4),
  ('mentor-13', 'Machine Learning', 5),
  ('mentor-13', 'Python', 5),
  ('mentor-13', 'Cloud Architecture', 3),
  ('mentor-13', 'SQL', 3),
  ('mentor-14', 'UX Research', 5),
  ('mentor-14', 'UI Design', 4),
  ('mentor-14', 'Product Strategy', 3),
  ('mentor-15', 'SQL', 5),
  ('mentor-15', 'Data Visualization', 5),
  ('mentor-15', 'Python', 4),
  ('mentor-15', 'Marketing Analytics', 3),
  ('mentor-16', 'Leadership', 5),
  ('mentor-16', 'Interviewing', 5),
  ('mentor-16', 'System Design', 4),
  ('mentor-16', 'Public Speaking', 3),
  ('mentor-17', 'React', 4),
  ('mentor-17', 'TypeScript', 4),
  ('mentor-17', 'UI Design', 3),
  ('mentor-17', 'Testing', 3),
  ('mentor-18', 'Cloud Architecture', 5),
  ('mentor-18', 'DevOps', 4),
  ('mentor-18', 'Kubernetes', 4),
  ('mentor-18', 'System Design', 4),
  ('mentor-19', 'Product Strategy', 4),
  ('mentor-19', 'Roadmapping', 5),
  ('mentor-19', 'UX Research', 3),
  ('mentor-19', 'Public Speaking', 3),
  ('mentor-20', 'DevOps', 5),
  ('mentor-20', 'Kubernetes', 4),
  ('mentor-20', 'Go', 3),
  ('mentor-20', 'Cloud Architecture', 4),
  ('mentor-21', 'Content Strategy', 5),
  ('mentor-21', 'Public Speaking', 4),
  ('mentor-21', 'Marketing Analytics', 3),
  ('mentor-22', 'Go', 5),
  ('mentor-22', 'SQL', 4),
  ('mentor-22', 'System Design', 3),
  ('mentor-22', 'Testing', 3),
  ('mentor-23', 'Leadership', 5),
  ('mentor-23', 'Interviewing', 4),
  ('mentor-23', 'System Design', 4),
  ('mentor-23', 'Public Speaking', 4),
  ('mentor-24', 'SQL', 5),
  ('mentor-24', 'Python', 4),
  ('mentor-24', 'Cloud Architecture', 3),
  ('mentor-24', 'Data Visualization', 3),
  ('mentor-25', 'UX Research', 5),
  ('mentor-25', 'Interviewing', 3),
  ('mentor-25', 'Product Strategy', 3),
  ('mentor-26', 'Public Speaking', 5),
  ('mentor-26', 'Content Strategy', 4),
  ('mentor-26', 'React', 3),
  ('mentor-26', 'Node.js', 3),
  ('mentor-27', 'Data Visualization', 4),
  ('mentor-27', 'SQL', 4),
  ('mentor-27', 'Product Strategy', 4),
  ('mentor-27', 'Marketing Analytics', 4),
  ('mentor-28', 'Application Security', 5),
  ('mentor-28', 'Cloud Architecture', 4),
  ('mentor-28', 'System Design', 3),
  ('mentor-29', 'Design Systems', 5),
  ('mentor-29', 'React', 4),
  ('mentor-29', 'UI Design', 4),
  ('mentor-29', 'TypeScript', 3),
  ('mentor-30', 'Fundraising', 5),
  ('mentor-30', 'Product Strategy', 4),
  ('mentor-30', 'Leadership', 4)
) as v(mentor_id, skill_name, proficiency) join skills s on s.name = v.skill_name;

insert into mentee_goal_skills (mentee_id, skill_id, priority)
select v.mentee_id, s.id, v.priority from (values
  ('mentee-01', 'React', 3),
  ('mentee-01', 'System Design', 3),
  ('mentee-01', 'Testing', 2),
  ('mentee-01', 'TypeScript', 1),
  ('mentee-02', 'Machine Learning', 3),
  ('mentee-02', 'Python', 3),
  ('mentee-02', 'SQL', 1),
  ('mentee-03', 'Design Systems', 3),
  ('mentee-03', 'UI Design', 3),
  ('mentee-03', 'UX Research', 1),
  ('mentee-04', 'Fundraising', 3),
  ('mentee-04', 'Public Speaking', 2),
  ('mentee-04', 'Product Strategy', 2),
  ('mentee-05', 'Cloud Architecture', 3),
  ('mentee-05', 'DevOps', 3),
  ('mentee-05', 'Kubernetes', 2),
  ('mentee-06', 'Leadership', 3),
  ('mentee-06', 'Interviewing', 2),
  ('mentee-06', 'System Design', 1),
  ('mentee-07', 'Marketing Analytics', 3),
  ('mentee-07', 'Content Strategy', 2),
  ('mentee-07', 'Data Visualization', 1),
  ('mentee-08', 'Product Strategy', 3),
  ('mentee-08', 'Roadmapping', 3),
  ('mentee-08', 'Public Speaking', 1),
  ('mentee-09', 'Application Security', 3),
  ('mentee-09', 'Cloud Architecture', 2),
  ('mentee-10', 'SQL', 3),
  ('mentee-10', 'Data Visualization', 3),
  ('mentee-10', 'Python', 1),
  ('mentee-11', 'React', 3),
  ('mentee-11', 'TypeScript', 2),
  ('mentee-11', 'Interviewing', 2),
  ('mentee-12', 'UX Research', 3),
  ('mentee-12', 'Product Strategy', 2),
  ('mentee-12', 'Interviewing', 1)
) as v(mentee_id, skill_name, priority) join skills s on s.name = v.skill_name;

commit;


notify pgrst, 'reload schema';

